### ISSUE TITLE
NotADirectoryError: [WinError 267]

### ISSUE THREAD

**Issue by mainaksh** [yshean/safari-video-downloader#3]
C:\temp\safari-video-downloader>python safari_downloader.py
youtube-dl is up-to-date (2018.04.16)
Traceback (most recent call last):
  File "safari_downloader.py", line 70, in <module>
    downloader.download()
  File "safari_downloader.py", line 48, in download
    os.makedirs(save_folder, exist_ok=True)
  File "C:\Users\Soni\AppData\Local\Programs\Python\Python36-32\lib\os.py", line
 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C://temp//vid
eos/Chapter 1 : Building Our Lab'

**Comment by mainaksh** [comment]
tried all combinations for OUTPUT_FOLDER = 'C:\\temp\\videos' or 'C:\temp\videos' or 'C:/temp/videos' or 'C://temp//videos' ---none worked

**Comment by fahimfss** [comment]
Had the same issue ... file name contained ':' in my case. workaround (safari_downloader.py): https://ideone.com/ib8n7W

**Comment by nabilazri** [comment]
thanks a lot fahim1993 :)

**Comment by ghost** [comment]
> Had the same issue ... file name contained ':' in my case. workaround (safari_downloader.py): https://ideone.com/ib8n7W

What do i do with this file? Please help me :)
