### ISSUE TITLE
ERROR: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by brianpooe** [yshean/safari-video-downloader#4]
ERROR: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\utils.py", line 1102, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

Traceback (most recent call last):
  File "safari_downloader.py", line 63, in <module>
    downloader.download()
  File "safari_downloader.py", line 41, in download
    os.makedirs(save_folder, exist_ok=True)
  File "C:\Users\BRIAN\AppData\Local\Programs\Python\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\docker series/Service Discovery - The Big "New" Piece'

**Comment by brianpooe** [comment]
same as issue #3
